# Generated by Django 5.2.7 on 2025-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISTANCE_1', models.FloatField(default=0)),
                ('DISTANCE_2', models.FloatField(default=0)),
                ('PAD_THICKNESS_1', models.FloatField(default=0)),
                ('PAD_THICKNESS_2', models.FloatField(default=0)),
                ('DISTANCE_3', models.FloatField(default=0)),
                ('DISTANCE_4', models.FloatField(default=0)),
            ],
        ),
    ]
